server:
  port: 8084

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: post-service
              uri: lb://post-service
              predicates:
                - Path=/api/posts/**
              filters:
                - RewritePath=/api/posts/(?<path>.*), /api/posts/$\{path}
            - id: post-service-base
              uri: lb://post-service
              predicates:
                - Path=/api/posts
            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/api/reviews/**
              filters:
                - RewritePath=/api/reviews/(?<path>.*), /api/reviews/$\{path}
            - id: review-service-base
              uri: lb://review-service
              predicates:
                - Path=/api/reviews
            - id: comment-service
              uri: lb://comment-service
              predicates:
                - Path=/api/comments/**
              filters:
                - RewritePath=/api/comments/(?<path>.*), /api/comments/$\{path}
            - id: comment-service-base
              uri: lb://comment-service
              predicates:
                - Path=/api/comments

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
